### ISSUE TITLE
Link generating but not working on victim phone

### ISSUE THREAD

**Issue by Devprajapati2003** [KasRoudra/CamHacker#1]
The link through your tool is generating but it works only on our phone . Not on victim phone 

Why  ???

**Comment by KasRoudra** [comment]
Give a try to this [solution](https://github.com/KasRoudra/pyphisher/issues/1) 
Let me know, if this solution fixes it!

**Comment by mjattu** [comment]
> Give a try to this [solution](https://github.com/KasRoudra/pyphisher/issues/1)D
> Let me know, if this solution fixes it!

Did you found any solution

**Comment by KasRoudra** [comment]
@mjattu Are you facing same issue?

**Comment by Bhattiadeel** [comment]
> The link through your tool is generating but it works only on our phone . Not on victim phone
> 
> Why ???

I have same problem

**Comment by KasRoudra** [comment]
@Bhattiadeel You need to authenticate ngrok account. Follow instructions below:
1. Create an account in [NGROK](https://ngrok.com)  and then log in
2. Go to [Authtoken](https://dashboard.ngrok.com/get-started/your-authtoken) 
3. Copy your authtoken
4. Open terminal and give command
`cd $HOME/.ngrokfolder && ./ngrok authtoken <your authtoken>`

 - Here replace `<your authtoken>` with one you copied from [here](https://dashboard.ngrok.com/get-started/your-authtoken) 
5. Press enter
6. Try CamHacker again
