### ISSUE TITLE
Arch Error

### ISSUE THREAD

**Issue by lisbonjoker** [KasRoudra/CamHacker#12]
I run the script as the instructions said, I checked the code and pacman is indeed mentioned but it gives me "[!] No supported package manager found! Install packages manually!"

**Comment by KasRoudra** [comment]
@lisbonjoker I've updated script. Can you please delete old one and retry with new?

**Comment by lisbonjoker** [comment]
`install: invalid option -- "y"`
but it installs and the script seems to be working now

**Comment by KasRoudra** [comment]
Okay. As it's working and I don't have any arch device we can ignore that warning. Thanks for your feedback to fix the script!
