### ISSUE TITLE
stuck at url-1

### ISSUE THREAD

**Issue by priyanshu00737** [KasRoudra/CamHacker#16]
it stucks at url-1 please fix this bug please

**Comment by KasRoudra** [comment]
@priyanshu00737 Have you solved this too?

**Comment by priyanshu00737** [comment]
Yes thanks for response can you update it and add some more features btw
it's awesome

**Comment by KasRoudra** [comment]
@priyanshu00737 Suggest some features

**Comment by priyanshu00737** [comment]
Umm I think so its great leave it as it is can you make a script in wich we
can send virus to other phone with a link or how can we control a phone
remotely by just sending a link please 🙏

**Comment by KasRoudra** [comment]
@priyanshu00737 Try [MetaSploit](https://github.com/rapid7/metasploit-framework)
