### ISSUE TITLE
Can't Use Cloudflared Tunnel 

### ISSUE THREAD

**Issue by febripranata** [KasRoudra/CamHacker#19]
i think cloudflare tunnel is better than ngrok, because ngrok has been labeled as unsafe internet, RED warning on the screen, it will definitely make people suspicious to open a link from us, Clodflare is still clean and not warned by google chrome, so please fix claudflare tunnel, because i prefer to use cludflare tunnel, than ngrok, but  this script always chooses ngrok since the latest update in 13 january 2022, sometimes he chooses cloudflare sometimes he chooses ngrok, can it not be made to choose manually options, or if you can turn everything like pyphisher, ngrok and cloudflared live together.

**Comment by febripranata** [comment]
I Chose Ngrok Still Cloudflare,
I Chose Cloudflare Still Cloudflare,
I Chose Ngrok Still Ngrok,
I Chose Cloudflare Still angrok,

![20220113_160844](https://user-images.githubusercontent.com/49566179/149299838-9b6acbbc-1ecf-40ad-8962-ba513a4741f1.jpg)
![20220113_160832](https://user-images.githubusercontent.com/49566179/149299859-78f299f8-bcb7-4bb6-baeb-67b21166a9b1.jpg)

**Comment by KasRoudra** [comment]
@febripranata Both ngrok and cloudflared has problems. Cloudflared servers go down frequently and results in no link. In that case you will never get cloudflared link even if you've chosen cloudflared.

**Comment by febripranata** [comment]
ok I understand, thank you for the response, can you make a script like camhacker, but this time a location tracker, phissing people to click on the link and turn on their GPS, like a seeker, but more simple and automatic like camhacker.

**Comment by KasRoudra** [comment]
@febripranata I think seeker is already the best solution for real time IP tracking. For phishing you can try my [PyPhisher](https://github.com/KasRoudra/PyPhisher) and for IP tracking you can try my [IP-Tracker](https://github.com/KasRoudra/IP-Tracker). Both will capture IP by link
