### ISSUE TITLE
cloudflared issue

### ISSUE THREAD

**Issue by priyanshu00737** [KasRoudra/CamHacker#20]
after the update it says to chosse a server between ngrok and cloudflared but why i chosses cloudflared it gives ngrok link but i preffer cloudflared please fix this bug as soon as possible thanks in advance

**Comment by priyanshu00737** [comment]
please disable ngrok cause i am always getting that link please make it like it was before i chosses clodflared still gets ngrok link i dont like ngrok so please disable it or is there any option to go back to older version of CamHacker ????????????????????/

**Comment by KasRoudra** [comment]
@priyanshu00737 Do you see `ngrok choosen` or `ngrok started`?

**Comment by priyanshu00737** [comment]
thanxs for update its fixed now
