### ISSUE TITLE
pictures is png

### ISSUE THREAD

**Issue by vexdes1** [KasRoudra/CamHacker#21]
when i do it , it works perfect but the pictures is png not jpg so can you fix it?

**Comment by KasRoudra** [comment]
What's wrong with jpg? Png is the default behaviour of script, not a bug

**Comment by vexdes1** [comment]
i mean i can't see the victim face you know?

**Comment by KasRoudra** [comment]
@vexdes1 That might be caused due to device security, his browser is preventing unauthorized camera access, or he didn't allow camera access, or he is using any light browser that doesn't support camera. Png is not responsible for this

**Comment by vexdes1** [comment]
thanks
