### ISSUE TITLE
Directory Windows 10

### ISSUE THREAD

**Issue by Kqrule** [KasRoudra/CamHacker#22]
How can i find photo directory on windows 10?

**Comment by KasRoudra** [comment]
@Kqrule This script is for linux, not windows. What is the directory shown in option i?

**Comment by Kqrule** [comment]
> @Kqrule This script is for linux, not windows. What is the directory shown in option i?

/home/user/CamHacker

**Comment by KasRoudra** [comment]
@Kqrule If you are using wsl, try [this](https://www.reddit.com/r/bashonubuntuonwindows/comments/9dkl12/sharing_files_between_windows_and_linux_wsl/)

**Comment by Kqrule** [comment]
> @Kqrule If you are using wsl, try [this](https://www.reddit.com/r/bashonubuntuonwindows/comments/9dkl12/sharing_files_between_windows_and_linux_wsl/)

I read it, I don’t know, until I try to run the program through the virtual machine, I’ll already see the photo there.  Thank you very much anyway, I'll read more about it later!

**Comment by Kqrule** [comment]
> @Kqrule If you are using wsl, try [this](https://www.reddit.com/r/bashonubuntuonwindows/comments/9dkl12/sharing_files_between_windows_and_linux_wsl/)

Mmm... So, how i need to use it? Im not a pro in this so how can i look for directory?)

**Comment by KasRoudra** [comment]
@Kqrule WSL is a linux terminal for windows. I think there you can find better file sharing than virtualbox or vmware. You can google to learn more about wsl.

**Comment by Kqrule** [comment]
> @Kqrule WSL is a linux terminal for windows. I think there you can find better file sharing than virtualbox or vmware. You can google to learn more about wsl.

Wait, can i just change directory from CamHacker terminal {i} to any folder in windows?

**Comment by KasRoudra** [comment]
@Kqrule Provide a screenshot of your camhacker
