### ISSUE TITLE
ARGO TUNNEL ERROR 

### ISSUE THREAD

**Issue by pgggfd** [KasRoudra/CamHacker#23]
argo tunnel error in online meeting using cloudflare

**Comment by KasRoudra** [comment]
@pgggfd That's a server related error. I've no access to it. Try using ngrok with authtoken.

**Comment by pgggfd** [comment]
its working good in all other like festival and jio there  is probleum in OM

**Comment by KasRoudra** [comment]
@pgggfd There is nothing unique in om. When you tried festival or jio, the server was good. But later on when you were trying with om, the server failed due to too many requests from users

**Comment by DerickCamp** [comment]
hello bro, I have a problem and it tells me tunneling failed when starting CamHacker to generate a link and I also tried to change it to ngrok but nothing, please help me and thanks <3.

**Comment by KasRoudra** [comment]
@DerickCamp Do you have authtoken for ngrok?

**Comment by 001zahi** [comment]
Bro are any camphish tool which use cloudflare server?

**Comment by 001zahi** [comment]
bcs,ngrok link does not work it showing security alert when i open in chrome

**Comment by KasRoudra** [comment]
@001zahi If Cloudflared server is ok, you will get cloudflared link from my CamHacker. When you don't get any link from ngrok or cloudflared that means the specific server is down

**Comment by Masterbrtm** [comment]
![IMG-20220412-WA0006](https://user-images.githubusercontent.com/99516926/163015501-c75b67ee-c459-498a-8c1c-ee6725935e03.jpg)
 
Ta dando falha no cloudflares e ngrok na minha primeira vez fuciona o resto n fuciona

**Comment by KasRoudra** [comment]
@Masterbrtm Cloudflared is temporaily down. Try again later after a couple of hours
