### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by Issho47** [KasRoudra/CamHacker#25]
Black Image

**Comment by KasRoudra** [comment]
@Issho47  Victim need to use good (not mini version like opera mini) browsers as chrome/brave/mozila to get image captured. Victim should allow camera access. Although some browsers can block this CamHacker, however it works in most devices.

**Comment by Issho47** [comment]
Please make discord phishing site cloudflared and ngrok.

**Comment by KasRoudra** [comment]
@Issho47 You have option to use custom domain like `is.gd` in pyphisher. You can use your own domain if you can buy that, we can't provide it.

**Comment by Issho47** [comment]
Sadly, there is no cloudflare option

**Comment by Issho47** [comment]
It's saying service not available

**Comment by KasRoudra** [comment]
@Issho47 Server often goes down for a while. Wait sometime and then try again

**Comment by Issho47** [comment]
Add cloudflare option coz ngrok was hijacked recently

**Comment by Issho47** [comment]
Yeah the server is down ig and ngrok sucks
