### ISSUE TITLE
how to see the images

### ISSUE THREAD

**Issue by WHITEDEVILV** [KasRoudra/CamHacker#27]
![image](https://user-images.githubusercontent.com/100081336/159113461-3ed06ffc-4595-4521-bed7-492e0ed01e39.png)

**Comment by KasRoudra** [comment]
@WHITEDEVILV Go to the given directory(which is shown in option i) from file explorer

**Comment by WHITEDEVILV** [comment]
I am in pc using a terminal

**Comment by KasRoudra** [comment]
@WHITEDEVILV So, you use pc but don't know how to open a directory in file explorer. Now, what can I do here? That's not related to my script. That's basic pc knowledge

**Comment by WHITEDEVILV** [comment]
lol btw your tool is just legendary bro nice work thnx to you

**Comment by KasRoudra** [comment]
@WHITEDEVILV Thanks. But how can you mark it as nice even without watching the photo🤔?

**Comment by WHITEDEVILV** [comment]
BRUH IT'S THE FIRST EVER LINK THAT HAS WORKED I AM GONNA TRY IT ON ANY OTHER OS I AM SURE I WILL GET HE PICS BUT I GOT  THE IP OF SOME PEOPLE THAT'S GOOD LIKED IT VERY MUCH THNX A LOT

**Comment by WHITEDEVILV** [comment]
WHERE DO YOU LIVE LIKE COUNTRY

**Comment by WHITEDEVILV** [comment]
BROOOOOOOO I GOT THE PICS LMAO THNX

**Comment by WHITEDEVILV** [comment]
I TRIED IT ON MYSELF

**Comment by KasRoudra** [comment]
@WHITEDEVILV You solved the problem on your own. Congrats! However, I am from Bangladesh

**Comment by WHITEDEVILV** [comment]
oo i am from delhi lmao

**Comment by KasRoudra** [comment]
@WHITEDEVILV So, you are my neighbour😄

**Comment by WHITEDEVILV** [comment]
Lol Yea 😂
