### ISSUE TITLE
Image is not Clear

### ISSUE THREAD

**Issue by 8himanshukk** [KasRoudra/CamHacker#28]
I SEND THIS LINK TO MY FRIEND BUT THE IMAGE SCREEN IS BLACK. WHAT SHOULD I DO????

**Comment by KasRoudra** [comment]
@8himanshukk Possibly he is using a secured browser which do not support photo stealing or he didn't allow camera access

**Comment by Steamwarriors12** [comment]
its of no use ... also the  geo location is wrong which the script provides.

**Comment by KasRoudra** [comment]
@Steamwarriors12 The geolocation is fetched from api. And read the readme, it doesn't work properly on some devices

**Comment by mahmoud01008** [comment]
How can I download the image
