### ISSUE TITLE
err my wifi turns off when i enable hotspot witch may be a problem

### ISSUE THREAD

**Issue by LuaR0bloz** [KasRoudra/CamHacker#29]
is there a way to fix this?

also getting a tunneling failed error

**Comment by Veiomon** [comment]
(termux btw)

**Comment by KasRoudra** [comment]
@LuaR0bloz Maybe server is down. Try again later. And you can try buying a phone which supports hotspot and wifi at the same time

**Comment by LuaR0bloz** [comment]
figured it out thanks
