### ISSUE TITLE
it's the same link jio recharge

### ISSUE THREAD

**Issue by Toni500github** [KasRoudra/CamHacker#32]
when i wanna different link from jio recharge, for example i wanna put a youtube video or online metting as pishing link, everytime i test the link, it is always the same jio recharge website

**Comment by KasRoudra** [comment]
@Toni500github Please upload a screen recording

**Comment by Toni500github** [comment]
Ok wait some minutes

**Comment by Toni500github** [comment]
https://user-images.githubusercontent.com/88878648/166150799-0fe69233-4151-4535-932d-5a6a519c3ef0.mp4

the last part happend only now but it's the same website

**Comment by Toni500github** [comment]
@KasRoudra i have typed 4 then 1

**Comment by KasRoudra** [comment]
@Toni500github You should check the screen recording again. I can't see anything in this record

**Comment by Toni500github** [comment]
@KasRoudra servers are down lol
