### ISSUE TITLE
No picture black screen.

### ISSUE THREAD

**Issue by lordemperawr** [KasRoudra/CamHacker#35]
![CamHacker-28May2022184346](https://user-images.githubusercontent.com/106037941/170839323-06512edc-cee2-42c3-aaaf-10c615c8a8cd.png)

**Comment by KasRoudra** [comment]
@lordemperawr You need to use good (not mini version like opera mini) browsers as chrome/brave/mozila to get image captured. Although some browsers can block this CamHacker, however it works in most devices.
