### ISSUE TITLE
How to open captured photos

### ISSUE THREAD

**Issue by ursme21221** [KasRoudra/CamHacker#37]
Please tell me how can I open captured photos in termux
Android mobile

**Comment by KasRoudra** [comment]
@ursme21221 In android, the captured photos are in `/sdcard/Pictures`. Search in Pictures folder of your internal storage. If you can't find, change directory in option i

**Comment by ursme21221** [comment]
Sir I can't find
Please help me

**Comment by ursme21221** [comment]
My mobile model redmi note 8 pro

**Comment by KasRoudra** [comment]
@ursme21221 Open your file manager and give screenshot here
