### ISSUE TITLE
PHP and tunneling failed

### ISSUE THREAD

**Issue by mihai132M** [KasRoudra/CamHacker#38]
Hello! I need some help...
![Screenshot_20220615-213734_Termux](https://user-images.githubusercontent.com/104884624/173900859-0941aabe-afb2-4e20-a34d-4c8edbec0858.jpg)
![Screenshot_20220615-213744_Termux](https://user-images.githubusercontent.com/104884624/173900887-1d18bc9b-c073-422b-859a-9fb52161b911.jpg)

**Comment by mihai132M** [comment]
Hotsppt mobil = mobile hotspot
Date mobile = mobile data

**Comment by KasRoudra** [comment]
@mihai132M Run this three commands and give screenshots
`cd $HOME/.cffolder && chmod 777 cloudflared`
`cd $HOME/.ngrokfolder && ngrok http 333`
`php -S 127.0.0.1:3333`

**Comment by mihai132M** [comment]
![Screenshot_20220616-054701_Termux](https://user-images.githubusercontent.com/104884624/173980343-57ec3bdd-6a46-4971-989c-dd5703aec12c.jpg)

**Comment by KasRoudra** [comment]
@mihai132M I asked to run separately. Run this two again

`cd $HOME/.cffolder && ./cloudflared tunnel --url 127.0.0.1:3333`

After taking a screenshot, close it and then run next one

`cd $HOME/.ngrokfolder && ./ngrok http 3333`

**Comment by mihai132M** [comment]
![Screenshot_20220616-062628_Termux](https://user-images.githubusercontent.com/104884624/173984633-56becc22-568f-46d9-bf32-cf9161ca6916.jpg)
![Screenshot_20220616-062635_Termux](https://user-images.githubusercontent.com/104884624/173984656-02cf604b-847c-48b5-ab06-1f020d23cccc.jpg)

**Comment by KasRoudra** [comment]
@mihai132M Before running any this you need to turn on hotspot. As you can see, without hotspot, none is working at all

**Comment by mihai132M** [comment]
![Screenshot_20220616-065200_Termux](https://user-images.githubusercontent.com/104884624/173987483-21c1afc7-d5cf-46ed-95f3-b4bb8b2a6a21.jpg)

What i do from here?

**Comment by mihai132M** [comment]
I can t write

**Comment by mihai132M** [comment]
I open a new session
![Screenshot_20220616-065445_Termux](https://user-images.githubusercontent.com/104884624/173987792-be8e39d5-4156-41e9-bb17-8bf3b6893e3b.jpg)

**Comment by mihai132M** [comment]
It's working! Merci beaucoup! <3
