### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Imjek** [KasRoudra/CamHacker#41]
I got error. [!] No supported package manager found! Install packages manually!

**Comment by KasRoudra** [comment]
@Imjek What is your operating system?

**Comment by Imjek** [comment]
Ish

**Comment by Imjek** [comment]
ISH bro

**Comment by Imjek** [comment]
does it work with ish?

**Comment by KasRoudra** [comment]
@Imjek It's not for ish. I wrote it for linux based os and android.

**Comment by Imjek** [comment]
Okay
