### ISSUE TITLE
Image received,but showing blank screen

### ISSUE THREAD

**Issue by gahanaiik12** [KasRoudra/CamHacker#42]
Image received
But showing green screen

**Comment by gahanaiik12** [comment]
Im using kali linux

**Comment by KasRoudra** [comment]
@gahanaiik12 Try with a different browser e.g Firefox/Brave

**Comment by gahanaiik12** [comment]
![Uploading 20220717_184936.jpg…]()
Like this

**Comment by gahanaiik12** [comment]
But most of the users use chrome right

**Comment by gahanaiik12** [comment]
Please suggest a way
Because most of the mobile users are chrome

**Comment by KasRoudra** [comment]
@gahanaiik12 Secured browsers can block the execution of this code. It can't be fixed. We can trap insecure browsers only
