### ISSUE TITLE
Tunneling failed! Start your own port forwarding/tunneling service at port 8080

### ISSUE THREAD

**Issue by R3Madara** [KasRoudra/CamHacker#43]
CamHacker was working fine for me until the update today I am getting this error:
Tunneling failed! Start your own port forwarding/tunneling service at port 8080
I also get it on VidPhisher too. I add ngrok Authtoken from https://dashboard.ngrok.com/get-started/your-authtoken when it asks for it but I still get this issue.
Please help us solve it, and Great work!

**Comment by KasRoudra** [comment]
@R3Madara For trobleshoot you can manually run this:
`cd $HOME/.tunneler && ./cloudflared tunnel -url 127.0.0.1:8080`
If you believe that this issue is for update, you can keep using version 1.4 by this:
`git checkout 1.4`
`./ch.sh --no-update`

**Comment by R3Madara** [comment]
hello  older version still works but the new one still has the error Tunneling failed! Start your own port forwarding/tunneling service at port 8080

**Comment by KasRoudra** [comment]
@R3Madara What is the operating system and username of your device?

**Comment by R3Madara** [comment]
thank you sir i think the problem is because i am using a vpn

**Comment by KasRoudra** [comment]
@R3Madara Is the issue solved now?

**Comment by R3Madara** [comment]
yes sir

**Comment by KasRoudra** [comment]
@R3Madara Okay thanks
