### ISSUE TITLE
There is no option to choose cloudflared or ngrok....

### ISSUE THREAD

**Issue by OrganicCrown3536** [KasRoudra/CamHacker#44]
![Screenshot_20220803-000356](https://user-images.githubusercontent.com/103399387/182515398-a929e030-653c-45ac-aa70-19346337b617.png)
As you can see, the option to choose cloudflared or ngrok does not appear...

**Comment by KasRoudra** [comment]
@OrganicCrown3536 There is no need to choose. By default camhacker will start every tunneler ngrok, cloudflared and loclx. You can specify url shortener to one by "-t" argument

**Comment by OrganicCrown3536** [comment]
> @OrganicCrown3536No hay necesidad de elegir. Por defecto, camhacker iniciará todos los túneles ngrok, cloudflared y loclx. Puede especificar el acortador de URL a uno con el argumento "-t"

The argument "t" does not appear and the tool does not start when choosing any of the first 3 options....

**Comment by KasRoudra** [comment]
@OrganicCrown3536 If you need other tunneler than cloudflared use "t" like `./ch.sh -t ngrok`. Otherwise, skip it.
