### ISSUE TITLE
empty picture

### ISSUE THREAD

**Issue by TrunksDeDBZ** [KasRoudra/CamHacker#47]
when I use with my phone it gives me an empty picture
![Capture d’écran_2022-09-02_07-55-19](https://user-images.githubusercontent.com/83141130/188137673-c6cb4710-03bc-460b-9b40-54ae6b25c66a.png)

**Comment by KasRoudra** [comment]
@TrunksDeDBZ What was the browser? Did you permit camera access?

**Comment by TrunksDeDBZ** [comment]
> @TrunksDeDBZ What was the browser? Did you permit camera access?

Google app in my iPhone

**Comment by KasRoudra** [comment]
@TrunksDeDBZ Unsupported for both camhacker and vidphisher. Try from brave/chrome/firefox

**Comment by TrunksDeDBZ** [comment]
> @TrunksDeDBZ Unsupported for both camhacker and vidphisher. Try from brave/chrome/firefox

Thanks you
