### ISSUE TITLE
Tunneling failed! Start your own tunneling service at port 8080 [!] PHP couldn't start!

### ISSUE THREAD

**Issue by gianne143** [KasRoudra/CamHacker#48]
Please fix this on old version

**Comment by KasRoudra** [comment]
@gianne143 Which version? Provide a screenshot

**Comment by gianne143** [comment]
![Screenshot_20220903-202716_Termux](https://user-images.githubusercontent.com/112745637/188270355-4284b4a2-2632-44fe-ab85-4e6628116278.jpg)

**Comment by gianne143** [comment]
It's version 1.5

**Comment by KasRoudra** [comment]
@gianne143 hotspot doesn't seem to be turned on
