### ISSUE TITLE
tunneling error in cloudflared, with option 1 of Jio Recharge

### ISSUE THREAD

**Issue by Darkrevengehack** [KasRoudra/CamHacker#49]
This appears to me within the cloudflared link: Error 1033
Ray ID: 745139e7d1222df4 •
2022-09-03 20:27:27 UTC
Argo Tunnel error
What happened?
You've requested a page on a website (edges-stockings-minds-uc.trycloudflare.com) that is on the Cloudflare network. The host (edges-stockings-minds-uc.trycloudflare.com) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Ensure that cloudflared is running and can reach the network. You may wish to enable [load balancing](https://developers.cloudflare.com/argo-tunnel/reference/load-balancing/) for your tunnel.

Was this page helpful? Yes No
Cloudflare Ray ID: 745139e7d1222df4
Your IP: Click to reveal
Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

**Comment by KasRoudra** [comment]
@Darkrevengehack Known error when cloudflared server has heavy traffic
