### ISSUE TITLE
Jio and Youtube open as Festival

### ISSUE THREAD

**Issue by tsiw247** [KasRoudra/CamHacker#5]
Jio Recharge and Youtube_live open as Festival can you help me solve this issues

**Comment by KasRoudra** [comment]
Such an issue is impossible unless you changed the code. 
Delete current camhacker (`rm -rf CamHacker`) and 
reclone again (`git clone https://github.com/KasRoudra/CamHacker`).
If problem still remains, provide a screen recording.
