### ISSUE TITLE
Chrome detecting ngrok link

### ISSUE THREAD

**Issue by NewtothisVvV** [KasRoudra/CamHacker#52]
So basically whenever I generate a link in this tool and  someones open it.it don't really opens because of Chrome security.I want an update to resolve this issue without the link being detected. Hope you release an update ASAP!

**Comment by KasRoudra** [comment]
@NewtothisVvV That's beyond our scope. You may try [MaxPhisher](https://github.com/KasRoudra/MaxPhisher) to potentially get two more links. Either cloudflared, or loclx or at least localhostrun should work fine

**Comment by DANGERHACKER007** [comment]
Use cloudeflare
