### ISSUE TITLE
Erro!

### ISSUE THREAD

**Issue by jokerrio** [KasRoudra/CamHacker#57]
Tunneling failed! Start your own port forwarding/tunneling service at port 8080

**Comment by KasRoudra** [comment]
@jokerrio Add a screenshot

**Comment by jokerrio** [comment]
![Screenshot_2023-02-03-11-11-54-461_com.termux.jpg](https://user-images.githubusercontent.com/83532868/216624792-4e1ef49d-b8bc-4fe1-8613-55a9bb514982.jpg)

**Comment by KasRoudra** [comment]
@jokerrio Turn on hotspot and restart termux

**Comment by jokerrio** [comment]
@KasRoudra I already did that, it doesn't work

**Comment by KasRoudra** [comment]
@jokerrio Check the error on your own by running `$HOME/.tunneler/ngrok http 8080`
