### ISSUE TITLE
PHP Couldn't start

### ISSUE THREAD

**Issue by IamLucif3r** [KasRoudra/CamHacker#6]
Hello there,
There is an error while executing the script, which says PHP could not start. 
I tried running it using SU, still the same result. 

![Screenshot at 2021-10-04 21-27-42](https://user-images.githubusercontent.com/53969258/135884199-32751d41-77c5-4d1e-a14b-e8a1254d0986.png)

**Comment by KasRoudra** [comment]
run this command to diagnose error:
`php -S 127.0.0.1:7777`
Let me know the command output

**Comment by IamLucif3r** [comment]
Alright it is already in use .
![image](https://user-images.githubusercontent.com/53969258/135886066-97b8795f-5e88-4d42-a147-99f76c11923d.png)

**Comment by KasRoudra** [comment]
`sed "s+7777+8888+g" ch.sh > c.sh`
`rm -rf ch.sh && mv c.sh ch.sh`
`sudo bash ch.sh`

**Comment by IamLucif3r** [comment]
Hey, I changed the address in your script, but Still the same problem coming
new address: 127.0.0.1:7788

**Comment by IamLucif3r** [comment]
Thanks man it is working now

**Comment by IamLucif3r** [comment]
Hey actually now the cloudflare is creating some problem.
It is showing that everything  is good from my end and the service
provider's end. But there is something bad at link's server

**Comment by KasRoudra** [comment]
Yeap, cloudflared server is pretty weak. That problem doesn't belong to my script. It may be fixed after you restart or retry later.
