### ISSUE TITLE
Dúvida (Doubt)

### ISSUE THREAD

**Issue by Odin-Hat** [KasRoudra/CamHacker#62]
<p>Olá boa noite, queria saber se para usar a ferramenta eu preciso usar em conjunto o ngrok aqui no termux?</p>

<p>Hello good evening, I wanted to know if to use the tool I need to use ngrok together here in termux?</p>

------------------------------------

Obs:. I'm using Google translate, sorry for any typos 

------------------------------------

**Comment by KasRoudra** [comment]
@Odin-Hat Using ngrok for phishing is againt tos of ngrok. I can't help you either
