### ISSUE TITLE
Where is the image saved at

### ISSUE THREAD

**Issue by NayanRoy123** [KasRoudra/CamHacker#67]

**Comment by KasRoudra** [comment]
@NayanRoy123 The directory mentioned in option `d`

**Comment by NayanRoy123** [comment]
@KasRoudra but I can't find it in my device folder.help

**Comment by KasRoudra** [comment]
@NayanRoy123 Which directory is mentioned?

**Comment by Bekkjj** [comment]
У меня стоит /sdcard/Camera где я могу посмотреть, в фаловом менеджере не показывает
