### ISSUE TITLE
Что делать с данной ошибкой?

### ISSUE THREAD

**Issue by Kiparisik** [KasRoudra/CamHacker#7]
![Screenshot_2021-10-04-20-01-37-972_com termux](https://user-images.githubusercontent.com/91907012/135893356-b037fe69-574e-48b0-80ec-a45d83cefe6d.jpg)

**Comment by KasRoudra** [comment]
Troubleshoot the problem with:
`php -S 127.0.0.1:7777`
Let me know the output!

**Comment by Kiparisik** [comment]
Все работает, спасибо!
