### ISSUE TITLE
Photo

### ISSUE THREAD

**Issue by T4y13** [KasRoudra/CamHacker#71]
How can i reach the photos? Pls help me im a beginner

**Comment by KasRoudra** [comment]
@T4y13 Your os?

**Comment by HeyIamJose** [comment]
@KasRoudra Hello, I have the same problem, I use termux on a phone and I don't know how to access the directory. Please help.

**Comment by KasRoudra** [comment]
@HeyIamJose Check Pictures folder in your internal storage

**Comment by HeyIamJose** [comment]
@KasRoudra Thanks I found the photos
